# What are the containers I'm going to build and those name one by one
version: '3.8'

services:
  redis:
    image: "redis:alpine"
    container_name: redis-container
    ports:
      - "6379:6379"

  app:
    container_name: flask-container
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - ./:/app
