# What are the containers I'm going to build and those name one by one
version: '3.8'

services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
